COEFFICIENTS: trip_mode_choice_coeffs.csv
CONSTANTS:
  I_AUTO_MODES:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  I_BIKE_MODE: 8
  I_DRIVE_TRANSIT_MODES:
  - 14
  - 15
  - 16
  - 17
  - 18
  I_MODE_MAP:
    BIKE: 8
    DRIVEALONEFREE: 1
    DRIVEALONEPAY: 2
    DRIVE_COM: 18
    DRIVE_EXP: 16
    DRIVE_HVY: 17
    DRIVE_LOC: 14
    DRIVE_LRF: 15
    SHARED2FREE: 3
    SHARED2PAY: 4
    SHARED3FREE: 5
    SHARED3PAY: 6
    TAXI: 19
    TNC_SHARED: 21
    TNC_SINGLE: 20
    WALK: 7
    WALK_COM: 13
    WALK_EXP: 11
    WALK_HVY: 12
    WALK_LOC: 9
    WALK_LRF: 10
  I_RIDE_HAIL_MODES:
  - 19
  - 20
  - 21
  I_SOV_MODES:
  - 1
  - 2
  I_SR2_MODES:
  - 3
  - 4
  I_SR3P_MODES:
  - 5
  - 6
  I_WALK_MODE: 7
  I_WALK_TRANSIT_MODES:
  - 9
  - 10
  - 11
  - 12
  - 13
  TNC_shared_IVTFactor: 1.5
  TNC_shared_baseFare: 2.2
  TNC_shared_costMinimum: 3.0
  TNC_shared_costPerMile: 0.53
  TNC_shared_costPerMinute: 0.1
  TNC_shared_waitTime_mean:
    1: 5.0
    2: 8.0
    3: 11.0
    4: 15.0
    5: 15.0
  TNC_shared_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_single_baseFare: 2.2
  TNC_single_costMinimum: 7.2
  TNC_single_costPerMile: 1.33
  TNC_single_costPerMinute: 0.24
  TNC_single_waitTime_mean:
    1: 3.0
    2: 6.3
    3: 8.4
    4: 8.5
    5: 10.3
  TNC_single_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  Taxi_baseFare: 2.2
  Taxi_costPerMile: 2.3
  Taxi_costPerMinute: 0.1
  Taxi_waitTime_mean:
    1: 5.5
    2: 9.5
    3: 13.3
    4: 17.3
    5: 26.5
  Taxi_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  bikeSpeed: 12.0
  bikeThresh: 6.0
  costPerMile: 23.29
  costShareSr2: 1.75
  costShareSr3: 2.5
  dest_col_name: destination
  longWalk: 0.667
  max_waitTime: 50
  min_waitTime: 0
  orig_col_name: origin
  shortWalk: 0.333
  waitThresh: 10.0
  walkSpeed: 3.0
  walkThresh: 1.0
LOGIT_TYPE: NL
MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
NESTS:
  alternatives:
  - alternatives:
    - alternatives:
      - DRIVEALONEFREE
      - DRIVEALONEPAY
      coefficient: 0.35
      name: DRIVEALONE
    - alternatives:
      - SHARED2FREE
      - SHARED2PAY
      coefficient: 0.35
      name: SHAREDRIDE2
    - alternatives:
      - SHARED3FREE
      - SHARED3PAY
      coefficient: 0.35
      name: SHAREDRIDE3
    coefficient: 0.72
    name: AUTO
  - alternatives:
    - WALK
    - BIKE
    coefficient: 0.72
    name: NONMOTORIZED
  - alternatives:
    - alternatives:
      - WALK_LOC
      - WALK_LRF
      - WALK_EXP
      - WALK_HVY
      - WALK_COM
      coefficient: 0.5
      name: WALKACCESS
    - alternatives:
      - DRIVE_LOC
      - DRIVE_LRF
      - DRIVE_EXP
      - DRIVE_HVY
      - DRIVE_COM
      coefficient: 0.5
      name: DRIVEACCESS
    coefficient: 0.72
    name: TRANSIT
  - alternatives:
    - TAXI
    - TNC_SINGLE
    - TNC_SHARED
    coefficient: 0.36
    name: RIDEHAIL
  coefficient: 1.0
  name: root
SPEC: trip_mode_choice.csv
TOURS_MERGED_CHOOSER_COLUMNS:
- hhsize
- age
- auto_ownership
- number_of_participants
- tour_category
- parent_tour_id
- tour_mode
- duration
- value_of_time
- tour_type
- free_parking_at_work
preprocessor:
  DF: df
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  TABLES:
  - land_use
  - tours
